# Generated by Django 6.1.1 on 2026-10-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('process', models.CharField(max_length=80)),
                ('quality', models.CharField(max_length=80)),
                ('stars', models.PositiveSmallIntegerField(default=5)),
                ('wholesale_price', models.PositiveIntegerField()),
                ('retail_price', models.PositiveIntegerField()),
                ('old_retail_price', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.CharField(default='۵ کیلو', max_length=40)),
                ('featured', models.BooleanField(default=False)),
                ('on_deal', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-featured', 'name'],
            },
        ),
    ]
