# Generated by Django 6.1.1 on 2026-10-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cook_steps',
            field=models.JSONField(blank=True, default=list, help_text='مراحل پخت'),
        ),
        migrations.AddField(
            model_name='product',
            name='cook_title',
            field=models.CharField(blank=True, default='دستور پخت روی اجاق', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='details_text',
            field=models.TextField(blank=True, help_text='متن تب جزئیات (اگر خالی باشد همان توضیحات اصلی استفاده می\u200cشود)'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='لیست ویژگی\u200cها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='متن معرفی زیر عنوان محصول'),
        ),
    ]
