# Generated by Django 6.1.1 on 2026-10-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_cook_steps_product_cook_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
