# Generated by Django 6.1.1 on 2026-10-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productreview_replied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.PositiveSmallIntegerField(default=0, help_text='میانگین امتیاز نظرات عمومی (۰ = بدون نظر)'),
        ),
    ]
