# Generated by Django 6.1.1 on 2026-10-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('brand_name', models.CharField(default='برنج رودی', max_length=80)),
                ('footer_tagline', models.CharField(default='برنج طبیعی ممتاز برای سفره\u200cهای ایرانی.', max_length=200)),
                ('about_title', models.CharField(default='کارخانه تخصصی برنج ایرانی به تمام عیار', max_length=160)),
                ('about_body', models.TextField(blank=True, default='ما متعهدیم بهترین برنج طبیعی را با کیفیت ثابت و طعمی ماندگار به سفره شما برسانیم.')),
                ('phone_numbers', models.JSONField(blank=True, default=list, help_text='لیست شماره تماس\u200cها')),
                ('working_hours', models.CharField(default='ساعات کاری شنبه تا پنجشنبه از ۹ الی ۱۸ و پشتیبانی آنلاین ۹ الی ۲۳', max_length=220)),
                ('factory_line', models.CharField(blank=True, default='کارخانه تخصصی برنج ایرانی به تمام عیار', max_length=200)),
                ('address_hq', models.TextField(default='تهران – جنوب به شمال بزرگراه نواب – لاین کندرو جوادیه – کوچه نظری ۱۲۱ – پلاک ۱۲ – ساختمان برنج آنلاین')),
                ('address_processing', models.TextField(blank=True, default='تهران - بزرگراه شهید چراغی - مجتمع تجاری پردیس کیان - واحد ۱۲۰')),
                ('email', models.EmailField(default='info@riceonline.ir', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات فروشگاه',
                'verbose_name_plural': 'تنظیمات فروشگاه',
            },
        ),
    ]
