# Generated by Django 6.1.1 on 2026-10-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cta_body',
            field=models.CharField(default='انواع برنج طبیعی را ببینید و سفارش خود را همین حالا ثبت کنید.', max_length=240),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button',
            field=models.CharField(default='مشاهده محصولات', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title',
            field=models.CharField(default='آماده خرید برنج ممتاز هستید؟', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_lead',
            field=models.TextField(default='برنج ۱۰۰٪ طبیعی و مغذی برای آشپزی خانگی و حرفه\u200cای. انتخاب مطمئن هزاران خانواده در سراسر کشور.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_primary_btn',
            field=models.CharField(default='خرید کنید', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_secondary_btn',
            field=models.CharField(default='تماس با ما', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(default='برای سفره\u200cهای سالم\u200cتر', max_length=160),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='برنج طبیعی ممتاز', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat1_label',
            field=models.CharField(default='کشاورز همکار', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat1_suffix',
            field=models.CharField(blank=True, default='هزار+', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat1_value',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat2_label',
            field=models.CharField(default='کیفیت بالاتر', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat2_suffix',
            field=models.CharField(blank=True, default='%', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat2_value',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat3_label',
            field=models.CharField(default='طبیعی', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat3_suffix',
            field=models.CharField(blank=True, default='%', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat3_value',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
