# Generated by Django 6.1.1 on 2026-10-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_sitesettings_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_kg',
            field=models.PositiveIntegerField(default=50, help_text='اگر موجودی از این مقدار کمتر شود، هشدار کمبود نمایش داده می\u200cشود'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_kg',
            field=models.PositiveIntegerField(default=500, help_text='موجودی فعلی انبار به کیلوگرم'),
        ),
    ]
