# Generated by Django 6.1.1 on 2026-10-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='اگر موجودی انبار برای این سفارش کم شده باشد True است'),
        ),
    ]
